version: '3.8'

services:
 nginx:
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  
  container_name: nginx
  ports:
   - "443:443"
  volumes:
   - wordpress_data:/var/www/html
  networks:
   - inception_network
  restart: always


networks:
 inception_network:
  driver: bridge

volumes:
 wordpress_data:
  driver: local
