version:  "3.8"
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context:  requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    image:  mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart:  on-failure
    expose:
      - "3306"

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build:
      context:  requirements/nginx
      dockerfile: Dockerfile
    image:  nginx
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  on-failure
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build:
      context:  requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - DOMAIN_NAME
        - SITE_TITLE
        - ADMIN_USER
        - ADMIN_PASS
        - ADMIN_EMAIL
        - USER0_LOGIN
        - USER0_MAIL
        - USER_PASS
    image:  wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  on-failure
    expose:
      - "9000"

networks:
    inception:
      driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/afaqir/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/afaqir/data/mariadb'

